name: "Publish org-roam to GitHub Pages"

runs:
  using: "composite"
  steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        repository: ikoamu/org-roam-ui-hosting
        path: action
    - name: "Checkout org file repo"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: orgs
    - name: Checkout org-roam-ui
      uses: actions/checkout@v4
      with:
        repository: ikoamu/org-roam-ui
        ref: feature/add-export-functionality
        path: ui

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "20.x"

    # create graphdata.json and notes
    - name: Install graphdata generator dependencies
      working-directory: action
      run: npm install
      shell: bash
    - name: Generate graphdata.json
      working-directory: action
      run: cat package.json
      shell: bash
    - name: Generate graphdata.json
      working-directory: action
      run: npm run generate --script_params=../orgs/org-roam.db
      shell: bash
    - name: Create Notes
      working-directory: action
      run: ./create_notes.sh ../orgs
      shell: bash

    # build org-roam-ui
    - name: Install org-roam-ui dependencies
      working-directory: ui
      run: yarn install
      shell: bash
    - name: Build org-roam-ui
      working-directory: ui/standalone
      run: ./build-standalone-server.sh ../../action/
      shell: bash
    - name: Add nojekyll
      working-directory: ui
      run: touch ./standalone/out/.nojekyll
      shell: bash
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "./ui/standalone/out"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
