name: "Publish org-roam to GitHub Pages"

runs:
  using: "composite"
  steps:
    # 呼び出されたworkflowのリポジトリをチェックアウトし、ファイル一覧を出力する
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: "repo"
    - name: "List files"
      run: |
        cd repo
        find . -type f
      shell: bash
